return {
	HUNTER = "HUNTER",
	WARLOCK = "WARLOCK",
	PRIEST = "PRIEST",
	PALADIN = "PALADIN",
	MAGE = "MAGE",
	ROGUE = "ROGUE",
	DRUID = "DRUID",
	SHAMAN = "SHAMAN",
	WARRIOR = "WARRIOR",
	DEATHKNIGHT = "DEATHKNIGHT",
	MONK = "MONK",
	DEMONHUNTER = "DEMONHUNTER",
}