return {
	POOR = LE_ITEM_QUALITY_POOR,
	COMMON = LE_ITEM_QUALITY_COMMON,
	UNCOMMON = LE_ITEM_QUALITY_UNCOMMON,
	RARE = LE_ITEM_QUALITY_RARE,
	EPIC = LE_ITEM_QUALITY_EPIC,
	LEGENDARY = LE_ITEM_QUALITY_LEGENDARY,
	ARTIFACT = LE_ITEM_QUALITY_ARTIFACT,
	HEIRLOOM = LE_ITEM_QUALITY_HEIRLOOM,
	WOW_TOKEN = LE_ITEM_QUALITY_WOW_TOKEN,
}